PADTRACKS=y
OUTPUTTYPE=flac
OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/${TRACKNUM}-${TRACKFILE}'
MAXPROCS=12
FLACOPTS=--best
EJECTCD=y
CDSPEEDVALUE=40
CDSPEEDOPTS=40,32,24,16,1
EXTRAVERBOSE=2
ACTIONS=cddb,read,encode,tag,embedalbumart,move,clean

